### ISSUE TITLE
Hi! I was checking the MDMFX code...and was running MDM FX...but...

### ISSUE THREAD

**Issue by ANGR77** [kajuk/MegaDrumManagerFX#2]
It seems like the firmware upgrade and options menus don't work in my downloaded build. (I took the last one) 

Does it work on your builds @kajuk ?

Best Regards

Anders

**Comment by kajuk** [comment]
I've tested it before uploading to Github. Try https://github.com/kajuk/MegaDrumManagerFX/commit/4615e6206f093cabd398188613a9d23f89a095ba - it is the commit which is published officially and where upgrade and options definitely work.

Regards
Dmitri

**Comment by ANGR77** [comment]
Hi! I tried that build but no luck with that build either. Is there any special thing which needs to be initiated to get these dialogs to run? When selecting these menu choices - nothing happens. Tried to check the code but I am unsure what is going on. (running on W10)

Best Regards
Anders

**Comment by kajuk** [comment]
But the official version works fine? In this case I'd suggest to set a
breakpoint on a non working event and step through to see what is going on.

**Comment by ANGR77** [comment]
No, no version works for me. So there is something wrong with my build. I made a short test with a breakpoint on the event...but the system could not trace the line....talking about that the quantum toolkit was missing...or something...:-)

I will look further...

**Comment by ANGR77** [comment]
The official compiled version of MDMFX works of course perfect.

When using breakpoints and really analysing the code and errors when klicking on "options" in MDMFX...I get the message: java.lang.UnsatisfiedLinkError: no mmj in java.library.path

What could this mean? The MMJ is defined as it supposed to.... :-)

**Comment by ANGR77** [comment]
Hallo again!

When I took out the reference to "mmj.jar" from the classpath file in the project root, then all of a sudden the whole thing started to execute as it supposed to. I am running on Windows 10 and the MMJ.Jar file is a midi lib for MAC. It looks like it fooled my implementation. 

Best Regards

Anders
